import { db } from "@workspace/db";
import {
  categoriesTable, locationsTable, jobsTable, startupIdeasTable, candidatesTable
} from "@workspace/db/schema";
import { count } from "drizzle-orm";
import { logger } from "../lib/logger.js";

const CATEGORIES = [
  { name: "Food & Beverage", description: "Restaurants, cafés, bakeries, food delivery", icon: "utensils" },
  { name: "Technology", description: "Software, SaaS, apps, digital platforms", icon: "cpu" },
  { name: "Healthcare", description: "Clinics, pharmacies, wellness, medical devices", icon: "heart-pulse" },
  { name: "Education", description: "Schools, training centers, e-learning platforms", icon: "graduation-cap" },
  { name: "Consulting", description: "Business advisory, management, HR consulting", icon: "briefcase" },
  { name: "Fitness & Wellness", description: "Gyms, spas, wellness centers, sports facilities", icon: "dumbbell" },
  { name: "Retail & Fashion", description: "Clothing, fashion brands, boutiques, accessories", icon: "shopping-bag" },
  { name: "Real Estate", description: "Property development, agencies, management", icon: "building" },
  { name: "Logistics", description: "Delivery, supply chain, freight, warehousing", icon: "truck" },
  { name: "Creative & Media", description: "Design studios, content creation, photography", icon: "palette" },
  { name: "Finance", description: "FinTech, investment, accounting, insurance", icon: "landmark" },
  { name: "Beauty & Personal Care", description: "Salons, spas, cosmetics, grooming", icon: "sparkles" },
];

const LOCATIONS = [
  { city: "Dubai", country: "UAE", region: "Middle East", sizeCategory: "metro" },
  { city: "Abu Dhabi", country: "UAE", region: "Middle East", sizeCategory: "large" },
  { city: "Riyadh", country: "Saudi Arabia", region: "Middle East", sizeCategory: "metro" },
  { city: "Jeddah", country: "Saudi Arabia", region: "Middle East", sizeCategory: "large" },
  { city: "Dammam", country: "Saudi Arabia", region: "Middle East", sizeCategory: "large" },
  { city: "Mecca", country: "Saudi Arabia", region: "Middle East", sizeCategory: "large" },
  { city: "Medina", country: "Saudi Arabia", region: "Middle East", sizeCategory: "medium" },
  { city: "Cairo", country: "Egypt", region: "North Africa", sizeCategory: "metro" },
  { city: "Alexandria", country: "Egypt", region: "North Africa", sizeCategory: "large" },
  { city: "Istanbul", country: "Turkey", region: "Europe/Asia", sizeCategory: "metro" },
  { city: "Ankara", country: "Turkey", region: "Europe/Asia", sizeCategory: "large" },
  { city: "Izmir", country: "Turkey", region: "Europe/Asia", sizeCategory: "large" },
  { city: "Beirut", country: "Lebanon", region: "Middle East", sizeCategory: "medium" },
  { city: "Doha", country: "Qatar", region: "Middle East", sizeCategory: "large" },
  { city: "Kuwait City", country: "Kuwait", region: "Middle East", sizeCategory: "large" },
  { city: "Manama", country: "Bahrain", region: "Middle East", sizeCategory: "medium" },
  { city: "Muscat", country: "Oman", region: "Middle East", sizeCategory: "large" },
  { city: "Amman", country: "Jordan", region: "Middle East", sizeCategory: "large" },
  { city: "Baghdad", country: "Iraq", region: "Middle East", sizeCategory: "metro" },
  { city: "Tehran", country: "Iran", region: "Middle East", sizeCategory: "metro" },
  { city: "Casablanca", country: "Morocco", region: "North Africa", sizeCategory: "large" },
  { city: "Tunis", country: "Tunisia", region: "North Africa", sizeCategory: "large" },
  { city: "Algiers", country: "Algeria", region: "North Africa", sizeCategory: "large" },
  { city: "Tripoli", country: "Libya", region: "North Africa", sizeCategory: "large" },
  { city: "Khartoum", country: "Sudan", region: "Africa", sizeCategory: "large" },
  { city: "Nairobi", country: "Kenya", region: "Africa", sizeCategory: "large" },
  { city: "Lagos", country: "Nigeria", region: "Africa", sizeCategory: "metro" },
  { city: "Abuja", country: "Nigeria", region: "Africa", sizeCategory: "large" },
  { city: "Accra", country: "Ghana", region: "Africa", sizeCategory: "large" },
  { city: "Addis Ababa", country: "Ethiopia", region: "Africa", sizeCategory: "large" },
  { city: "Dar es Salaam", country: "Tanzania", region: "Africa", sizeCategory: "large" },
  { city: "Johannesburg", country: "South Africa", region: "Africa", sizeCategory: "metro" },
  { city: "Cape Town", country: "South Africa", region: "Africa", sizeCategory: "large" },
  { city: "New York", country: "USA", region: "North America", sizeCategory: "metro" },
  { city: "Los Angeles", country: "USA", region: "North America", sizeCategory: "metro" },
  { city: "Chicago", country: "USA", region: "North America", sizeCategory: "metro" },
  { city: "Houston", country: "USA", region: "North America", sizeCategory: "metro" },
  { city: "Miami", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "San Francisco", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "Seattle", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "Austin", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "Boston", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "Dallas", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "Phoenix", country: "USA", region: "North America", sizeCategory: "large" },
  { city: "Denver", country: "USA", region: "North America", sizeCategory: "medium" },
  { city: "Boise", country: "USA", region: "North America", sizeCategory: "medium" },
  { city: "Toronto", country: "Canada", region: "North America", sizeCategory: "metro" },
  { city: "Vancouver", country: "Canada", region: "North America", sizeCategory: "large" },
  { city: "London", country: "UK", region: "Europe", sizeCategory: "metro" },
  { city: "Manchester", country: "UK", region: "Europe", sizeCategory: "large" },
  { city: "Birmingham", country: "UK", region: "Europe", sizeCategory: "large" },
  { city: "Paris", country: "France", region: "Europe", sizeCategory: "metro" },
  { city: "Lyon", country: "France", region: "Europe", sizeCategory: "large" },
  { city: "Berlin", country: "Germany", region: "Europe", sizeCategory: "metro" },
  { city: "Munich", country: "Germany", region: "Europe", sizeCategory: "large" },
  { city: "Frankfurt", country: "Germany", region: "Europe", sizeCategory: "large" },
  { city: "Amsterdam", country: "Netherlands", region: "Europe", sizeCategory: "large" },
  { city: "Madrid", country: "Spain", region: "Europe", sizeCategory: "metro" },
  { city: "Barcelona", country: "Spain", region: "Europe", sizeCategory: "large" },
  { city: "Rome", country: "Italy", region: "Europe", sizeCategory: "metro" },
  { city: "Milan", country: "Italy", region: "Europe", sizeCategory: "large" },
  { city: "Zurich", country: "Switzerland", region: "Europe", sizeCategory: "large" },
  { city: "Vienna", country: "Austria", region: "Europe", sizeCategory: "large" },
  { city: "Stockholm", country: "Sweden", region: "Europe", sizeCategory: "large" },
  { city: "Copenhagen", country: "Denmark", region: "Europe", sizeCategory: "large" },
  { city: "Oslo", country: "Norway", region: "Europe", sizeCategory: "large" },
  { city: "Helsinki", country: "Finland", region: "Europe", sizeCategory: "large" },
  { city: "Warsaw", country: "Poland", region: "Europe", sizeCategory: "large" },
  { city: "Prague", country: "Czech Republic", region: "Europe", sizeCategory: "large" },
  { city: "Athens", country: "Greece", region: "Europe", sizeCategory: "large" },
  { city: "Lisbon", country: "Portugal", region: "Europe", sizeCategory: "large" },
  { city: "Brussels", country: "Belgium", region: "Europe", sizeCategory: "large" },
  { city: "Moscow", country: "Russia", region: "Europe/Asia", sizeCategory: "metro" },
  { city: "Mumbai", country: "India", region: "South Asia", sizeCategory: "metro" },
  { city: "Delhi", country: "India", region: "South Asia", sizeCategory: "metro" },
  { city: "Bangalore", country: "India", region: "South Asia", sizeCategory: "metro" },
  { city: "Hyderabad", country: "India", region: "South Asia", sizeCategory: "large" },
  { city: "Chennai", country: "India", region: "South Asia", sizeCategory: "large" },
  { city: "Karachi", country: "Pakistan", region: "South Asia", sizeCategory: "metro" },
  { city: "Lahore", country: "Pakistan", region: "South Asia", sizeCategory: "large" },
  { city: "Dhaka", country: "Bangladesh", region: "South Asia", sizeCategory: "metro" },
  { city: "Colombo", country: "Sri Lanka", region: "South Asia", sizeCategory: "large" },
  { city: "Beijing", country: "China", region: "East Asia", sizeCategory: "metro" },
  { city: "Shanghai", country: "China", region: "East Asia", sizeCategory: "metro" },
  { city: "Shenzhen", country: "China", region: "East Asia", sizeCategory: "metro" },
  { city: "Guangzhou", country: "China", region: "East Asia", sizeCategory: "metro" },
  { city: "Hong Kong", country: "China", region: "East Asia", sizeCategory: "metro" },
  { city: "Tokyo", country: "Japan", region: "East Asia", sizeCategory: "metro" },
  { city: "Osaka", country: "Japan", region: "East Asia", sizeCategory: "large" },
  { city: "Seoul", country: "South Korea", region: "East Asia", sizeCategory: "metro" },
  { city: "Singapore", country: "Singapore", region: "Southeast Asia", sizeCategory: "metro" },
  { city: "Bangkok", country: "Thailand", region: "Southeast Asia", sizeCategory: "metro" },
  { city: "Jakarta", country: "Indonesia", region: "Southeast Asia", sizeCategory: "metro" },
  { city: "Kuala Lumpur", country: "Malaysia", region: "Southeast Asia", sizeCategory: "large" },
  { city: "Manila", country: "Philippines", region: "Southeast Asia", sizeCategory: "metro" },
  { city: "Ho Chi Minh City", country: "Vietnam", region: "Southeast Asia", sizeCategory: "large" },
  { city: "Sydney", country: "Australia", region: "Oceania", sizeCategory: "metro" },
  { city: "Melbourne", country: "Australia", region: "Oceania", sizeCategory: "metro" },
  { city: "Auckland", country: "New Zealand", region: "Oceania", sizeCategory: "large" },
  { city: "São Paulo", country: "Brazil", region: "South America", sizeCategory: "metro" },
  { city: "Buenos Aires", country: "Argentina", region: "South America", sizeCategory: "metro" },
  { city: "Bogotá", country: "Colombia", region: "South America", sizeCategory: "metro" },
  { city: "Mexico City", country: "Mexico", region: "North America", sizeCategory: "metro" },
];

const JOBS = [
  {
    title: "Senior Full-Stack Developer",
    company: "TechVenture Labs",
    description: "Lead development of our SaaS platform. Build and maintain scalable microservices, work with cross-functional teams, and mentor junior developers. Strong emphasis on TypeScript, React, and Node.js.",
    requiredSkills: "React, Node.js, PostgreSQL, TypeScript, AWS",
    salaryMin: 110000,
    salaryMax: 150000,
    jobType: "full-time",
    location: "New York, NY",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "Financial Analyst",
    company: "Capital Bridge Partners",
    description: "Analyze investment opportunities, build financial models, and prepare detailed reports for private equity clients. You'll work on deal evaluation and portfolio monitoring.",
    requiredSkills: "Financial modeling, Excel, Bloomberg, CFA preferred, PowerBI",
    salaryMin: 75000,
    salaryMax: 105000,
    jobType: "full-time",
    location: "Dubai, UAE",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Product Marketing Manager",
    company: "GrowthEdge Inc",
    description: "Own go-to-market strategy for our B2B analytics product. Work closely with Product and Sales to craft compelling positioning and drive pipeline growth.",
    requiredSkills: "GTM strategy, copywriting, HubSpot, A/B testing, Salesforce",
    salaryMin: 85000,
    salaryMax: 120000,
    jobType: "full-time",
    location: "San Francisco, CA",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Data Scientist",
    company: "IntelliMetrics AI",
    description: "Build predictive models for retail demand forecasting. Work with large-scale datasets, MLOps pipelines, and deploy models into production using Python and cloud infrastructure.",
    requiredSkills: "Python, TensorFlow, SQL, Spark, MLflow, Azure ML",
    salaryMin: 120000,
    salaryMax: 165000,
    jobType: "full-time",
    location: "London, UK",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "Business Development Representative",
    company: "ScaleUp Ventures",
    description: "Identify and qualify new business opportunities. Manage outreach campaigns, book discovery calls, and hand off qualified leads to Account Executives. KPI-driven environment.",
    requiredSkills: "CRM (Salesforce), cold outreach, communication, negotiation",
    salaryMin: 55000,
    salaryMax: 75000,
    jobType: "full-time",
    location: "Miami, FL",
    experienceLevel: "entry",
    isActive: true,
  },
  {
    title: "UX/UI Designer",
    company: "PixelCraft Studio",
    description: "Design intuitive digital experiences for enterprise clients across mobile and web. Lead user research, wireframing, and high-fidelity prototyping in Figma. Collaborate with developers for pixel-perfect handoff.",
    requiredSkills: "Figma, user research, prototyping, design systems, Webflow",
    salaryMin: 70000,
    salaryMax: 95000,
    jobType: "full-time",
    location: "Amsterdam, Netherlands",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Operations Manager",
    company: "LogiFlow Solutions",
    description: "Oversee day-to-day operations for our logistics platform. Manage a team of 12, improve process efficiency using Lean methodologies, and report directly to the COO.",
    requiredSkills: "Operations management, supply chain, Lean Six Sigma, leadership, ERP systems",
    salaryMin: 80000,
    salaryMax: 110000,
    jobType: "full-time",
    location: "Houston, TX",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "Content Marketing Specialist",
    company: "BrandWise Agency",
    description: "Create compelling content across blog, social media, email, and video. Develop editorial calendars, optimize for SEO, and analyze performance to continuously improve content ROI.",
    requiredSkills: "Content writing, SEO, social media, email marketing, Google Analytics",
    salaryMin: 50000,
    salaryMax: 70000,
    jobType: "part-time",
    location: "Remote",
    experienceLevel: "entry",
    isActive: true,
  },
  {
    title: "Healthcare Clinic Manager",
    company: "Pulse Medical Group",
    description: "Manage daily clinic operations including scheduling, staff management, patient experience, and regulatory compliance. Coordinate with physicians and insurance partners.",
    requiredSkills: "Healthcare administration, scheduling, compliance, patient relations, EMR systems",
    salaryMin: 60000,
    salaryMax: 85000,
    jobType: "full-time",
    location: "Dubai, UAE",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "E-Commerce Growth Manager",
    company: "ShopFront Digital",
    description: "Drive online revenue growth through performance marketing, CRO, and customer lifecycle programs. Own P&L for our DTC brand. Experience with Shopify and Meta Ads required.",
    requiredSkills: "Shopify, Meta Ads, Google Ads, CRO, email marketing, analytics",
    salaryMin: 75000,
    salaryMax: 100000,
    jobType: "full-time",
    location: "Toronto, Canada",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Restaurant General Manager",
    company: "Noor Hospitality Group",
    description: "Lead all aspects of restaurant operations including service quality, cost control, staff recruitment, and compliance. Responsible for hitting monthly revenue and NPS targets.",
    requiredSkills: "F&B operations, P&L management, staff training, inventory, POS systems",
    salaryMin: 55000,
    salaryMax: 80000,
    jobType: "full-time",
    location: "Riyadh, Saudi Arabia",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "Real Estate Investment Analyst",
    company: "Horizon Property Group",
    description: "Evaluate commercial and residential investment opportunities across MENA. Perform DCF analysis, risk assessment, and present findings to investment committee.",
    requiredSkills: "Financial analysis, DCF modeling, real estate law basics, Excel, Argus",
    salaryMin: 65000,
    salaryMax: 90000,
    jobType: "full-time",
    location: "Abu Dhabi, UAE",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Digital Marketing Manager",
    company: "Nexus Brands MENA",
    description: "Lead multi-channel digital marketing campaigns across paid social, Google, and programmatic for 3 consumer brands. Manage a $500k monthly ad budget and a team of 4 specialists.",
    requiredSkills: "Performance marketing, Meta Ads, Google Ads, analytics, budget management",
    salaryMin: 70000,
    salaryMax: 95000,
    jobType: "full-time",
    location: "Dubai, UAE",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Cybersecurity Engineer",
    company: "SecureNet Technologies",
    description: "Design and implement security frameworks for cloud-native infrastructure. Conduct penetration testing, vulnerability assessments, and incident response. CISSP or CEH preferred.",
    requiredSkills: "Penetration testing, AWS Security, SIEM tools, incident response, CISSP",
    salaryMin: 130000,
    salaryMax: 180000,
    jobType: "full-time",
    location: "London, UK",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "Supply Chain Coordinator",
    company: "Global Trade Partners",
    description: "Coordinate international shipments, manage supplier relationships, and optimize inventory levels across 5 countries. Fluent Arabic and English required.",
    requiredSkills: "SAP, inventory management, international logistics, Arabic, Excel",
    salaryMin: 45000,
    salaryMax: 65000,
    jobType: "full-time",
    location: "Cairo, Egypt",
    experienceLevel: "entry",
    isActive: true,
  },
  {
    title: "Fitness & Wellness Director",
    company: "CoreLife Gym Chain",
    description: "Lead operations for 5 gym locations. Oversee personal training programs, class schedules, member retention, and partner with nutritionists and physio teams.",
    requiredSkills: "Fitness programming, staff management, member retention, P&L, fitness certifications",
    salaryMin: 65000,
    salaryMax: 90000,
    jobType: "full-time",
    location: "Istanbul, Turkey",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "AI/ML Engineer",
    company: "NeuralStack Labs",
    description: "Build and deploy large language model applications for enterprise clients. Fine-tune foundation models, design RAG pipelines, and ship production-ready AI products.",
    requiredSkills: "Python, PyTorch, LangChain, RAG, vector databases, cloud deployment",
    salaryMin: 140000,
    salaryMax: 190000,
    jobType: "full-time",
    location: "San Francisco, CA",
    experienceLevel: "senior",
    isActive: true,
  },
  {
    title: "Customer Success Manager",
    company: "Propel SaaS",
    description: "Manage a portfolio of 80+ mid-market SaaS accounts. Drive adoption, reduce churn, and identify upsell opportunities. Own Net Revenue Retention targets.",
    requiredSkills: "SaaS customer success, Gainsight, CRM, communication, data analysis",
    salaryMin: 70000,
    salaryMax: 95000,
    jobType: "full-time",
    location: "Remote",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Brand Designer",
    company: "Artform Creative Studio",
    description: "Create visual identities for fast-growing startups and established brands. Deliverables include logos, brand guidelines, packaging, and marketing materials.",
    requiredSkills: "Figma, Adobe Illustrator, Photoshop, typography, brand strategy",
    salaryMin: 55000,
    salaryMax: 75000,
    jobType: "freelance",
    location: "Remote",
    experienceLevel: "mid",
    isActive: true,
  },
  {
    title: "Pharmacy Manager",
    company: "MediCare Pharmacy Chain",
    description: "Manage all aspects of pharmacy operations including dispensing accuracy, staff scheduling, inventory, and regulatory compliance. Pharmacist license required.",
    requiredSkills: "Pharmacy license, inventory management, compliance, staff training, POS/dispensing software",
    salaryMin: 80000,
    salaryMax: 110000,
    jobType: "full-time",
    location: "Kuwait City, Kuwait",
    experienceLevel: "senior",
    isActive: true,
  },
];

const STARTUP_IDEAS = [
  {
    title: "AI-Powered Legal Assistant",
    description: "SaaS platform that uses GPT-4 to help small law firms automate contract review, due diligence, and client intake. Reduces manual work by 70% and delivers results in minutes rather than hours.",
    category: "Technology",
    requiredBudget: 500000,
    expectedReturn: 3.2,
    riskLevel: "Medium",
    stage: "mvp",
    isFeatured: true,
  },
  {
    title: "Urban Vertical Farm Network",
    description: "Hydroponic farming pods installed in urban warehouses and restaurant basements, supplying hyper-fresh produce locally within 24 hours. Subscription model for restaurants and grocery chains.",
    category: "Food & Beverage",
    requiredBudget: 750000,
    expectedReturn: 2.8,
    riskLevel: "Medium",
    stage: "prototype",
    isFeatured: true,
  },
  {
    title: "On-Demand Skilled Trades Platform",
    description: "Like Uber but for licensed electricians, plumbers, and HVAC technicians. Real-time job matching, instant booking, transparent pricing, and verified license checks. Addresses the massive skilled trades shortage.",
    category: "Logistics",
    requiredBudget: 600000,
    expectedReturn: 3.8,
    riskLevel: "Medium",
    stage: "growth",
    isFeatured: true,
  },
  {
    title: "Smart Home Energy Optimizer",
    description: "IoT device + AI software that reduces household energy bills by 30–40% through intelligent automation of HVAC, lighting, and appliances. Learns usage patterns and optimizes in real-time.",
    category: "Technology",
    requiredBudget: 400000,
    expectedReturn: 2.5,
    riskLevel: "Medium",
    stage: "mvp",
    isFeatured: true,
  },
  {
    title: "Sustainable Packaging Marketplace",
    description: "B2B marketplace connecting brands with verified eco-friendly packaging suppliers. Certification system, carbon footprint calculator, and bulk ordering with 30% cost savings vs. traditional channels.",
    category: "Retail & Fashion",
    requiredBudget: 300000,
    expectedReturn: 2.2,
    riskLevel: "Low",
    stage: "idea",
    isFeatured: false,
  },
  {
    title: "EdTech for Blue-Collar Skills",
    description: "Online platform offering certified vocational training for in-demand trades — welding, electrical, CNC machining. Employer partnerships guarantee placement for top graduates within 90 days.",
    category: "Education",
    requiredBudget: 350000,
    expectedReturn: 2.9,
    riskLevel: "Low",
    stage: "growth",
    isFeatured: true,
  },
  {
    title: "Mental Health Super App",
    description: "All-in-one mental health platform combining AI therapy chatbot, licensed therapist video sessions, mood tracking, and crisis intervention. Monthly subscription with employer plan options.",
    category: "Healthcare",
    requiredBudget: 800000,
    expectedReturn: 4.1,
    riskLevel: "High",
    stage: "prototype",
    isFeatured: false,
  },
  {
    title: "Halal Food Subscription Box",
    description: "Premium curated halal meal kits delivered weekly to Muslim households in Western countries. Gourmet recipes, pre-portioned ingredients, and certified halal sourcing from local farms.",
    category: "Food & Beverage",
    requiredBudget: 200000,
    expectedReturn: 2.1,
    riskLevel: "Low",
    stage: "idea",
    isFeatured: false,
  },
  {
    title: "Corporate Wellness Platform",
    description: "B2B wellness platform offering employees personalized fitness plans, mental health resources, nutrition coaching, and biometric tracking. Proven to reduce insurance costs by 18%.",
    category: "Fitness & Wellness",
    requiredBudget: 450000,
    expectedReturn: 3.0,
    riskLevel: "Medium",
    stage: "mvp",
    isFeatured: false,
  },
  {
    title: "Real Estate Tokenization Platform",
    description: "Blockchain-based platform allowing investors to buy fractional ownership in commercial real estate starting from $500. Full regulatory compliance (SEC), automatic dividend distribution.",
    category: "Finance",
    requiredBudget: 1200000,
    expectedReturn: 5.0,
    riskLevel: "High",
    stage: "prototype",
    isFeatured: true,
  },
  {
    title: "AI Interior Design Studio",
    description: "Upload photos of your space, set your budget, and receive a complete interior design plan with furniture recommendations, 3D renders, and a vetted contractor network for execution.",
    category: "Creative & Media",
    requiredBudget: 250000,
    expectedReturn: 2.6,
    riskLevel: "Low",
    stage: "mvp",
    isFeatured: false,
  },
  {
    title: "Micro-Logistics for Dark Stores",
    description: "Build a network of 500 sq ft dark stores in urban neighborhoods enabling 15-minute grocery delivery. AI demand forecasting, robotic picking assistance, and hyperlocal last-mile delivery.",
    category: "Logistics",
    requiredBudget: 900000,
    expectedReturn: 3.5,
    riskLevel: "High",
    stage: "growth",
    isFeatured: false,
  },
];

const CANDIDATES = [
  {
    name: "Sarah Chen", title: "Senior Software Engineer", bio: "Full-stack engineer with 8 years building SaaS products at Y Combinator startups. Expert in React, Node.js, and distributed systems.",
    skills: "React, Node.js, TypeScript, PostgreSQL, AWS, Docker", location: "San Francisco, CA", yearsExperience: 8, monthlyRate: 12000, availability: "available", categories: "tech,saas,software",
  },
  {
    name: "Omar Al-Rashid", title: "Operations Manager", bio: "10 years managing operations for F&B chains across GCC. Opened 12 restaurant locations. Expert in cost control, supply chain, and staff development.",
    skills: "Operations, P&L, supply chain, F&B, team management, ERP", location: "Dubai, UAE", yearsExperience: 10, monthlyRate: 8000, availability: "available", categories: "restaurant,food,cafe,hospitality",
  },
  {
    name: "Priya Sharma", title: "Digital Marketing Director", bio: "Led digital growth for 3 funded startups from 0 to $10M ARR. Specializes in performance marketing, SEO, and lifecycle email campaigns.",
    skills: "Meta Ads, Google Ads, SEO, HubSpot, analytics, email", location: "Mumbai, India", yearsExperience: 9, monthlyRate: 7500, availability: "available", categories: "ecommerce,retail,tech,saas",
  },
  {
    name: "James Okafor", title: "Financial Analyst", bio: "CFA charterholder with experience at BlackRock and two high-growth startups. Builds detailed financial models and investor-ready pitch decks.",
    skills: "Financial modeling, Excel, Bloomberg, CFA, PowerBI, DCF", location: "London, UK", yearsExperience: 7, monthlyRate: 9500, availability: "available", categories: "finance,consulting,real estate,investment",
  },
  {
    name: "Layla Al-Dosari", title: "Healthcare Administrator", bio: "Clinical operations specialist who has set up and managed 4 private clinics across Qatar and UAE. Expert in licensing, insurance billing, and patient experience.",
    skills: "Clinic management, EMR, compliance, insurance billing, Arabic, English", location: "Doha, Qatar", yearsExperience: 6, monthlyRate: 6500, availability: "available", categories: "healthcare,clinic,pharmacy,wellness",
  },
  {
    name: "Carlos Rivera", title: "Head of Sales", bio: "Built and led sales teams from scratch at 2 B2B SaaS companies. Closed $8M in ARR in the last 2 years. Expert in outbound prospecting and deal negotiation.",
    skills: "B2B sales, Salesforce, outbound, negotiation, SaaS, pipeline management", location: "Mexico City, Mexico", yearsExperience: 11, monthlyRate: 10000, availability: "available", categories: "saas,tech,consulting,b2b",
  },
  {
    name: "Fatima Al-Zahra", title: "Brand & Creative Director", bio: "Built brand identities for 40+ MENA-based companies from fintech to lifestyle. Expert in visual systems, Arabic typography, and campaign strategy.",
    skills: "Figma, Illustrator, brand strategy, Arabic typography, campaign design", location: "Riyadh, Saudi Arabia", yearsExperience: 8, monthlyRate: 7000, availability: "available", categories: "retail,fashion,media,beauty,creative",
  },
  {
    name: "Yuki Tanaka", title: "Product Manager", bio: "5 years leading product at Tokyo-based SaaS companies. Shipped 3 products from 0 to 50k users. Deep expertise in agile delivery and user research.",
    skills: "Product roadmap, user research, agile, Jira, Figma, analytics", location: "Tokyo, Japan", yearsExperience: 5, monthlyRate: 8500, availability: "busy", categories: "tech,saas,software,app",
  },
  {
    name: "Ahmed Khalil", title: "Logistics & Supply Chain Expert", bio: "15 years in international freight and last-mile delivery. Reduced logistics costs by 22% for a $200M retailer. Deep knowledge of GCC customs and fulfillment networks.",
    skills: "Logistics, SAP, warehouse management, customs, procurement, Arabic", location: "Cairo, Egypt", yearsExperience: 15, monthlyRate: 6000, availability: "available", categories: "logistics,delivery,import,wholesale",
  },
  {
    name: "Isabella Santos", title: "Culinary Director / Head Chef", bio: "Executive chef with Michelin experience. Opened 5 restaurants across Europe and Brazil. Specializes in concept development, menu engineering, and kitchen management.",
    skills: "Menu development, kitchen ops, food costing, HACCP, team training", location: "São Paulo, Brazil", yearsExperience: 12, monthlyRate: 7500, availability: "available", categories: "restaurant,cafe,food,hospitality",
  },
  {
    name: "Daniel Osei", title: "Real Estate Analyst", bio: "Analyzed $800M+ in real estate transactions across West Africa and Europe. Specialize in DCF modeling, market feasibility studies, and due diligence reports.",
    skills: "DCF modeling, Argus, market research, due diligence, Excel, PowerPoint", location: "Lagos, Nigeria", yearsExperience: 6, monthlyRate: 5500, availability: "available", categories: "real estate,property,construction",
  },
  {
    name: "Mei Lin", title: "Data Engineer", bio: "Built data pipelines processing 2B+ events/day at Alibaba Cloud. Expert in Spark, Kafka, and modern data stack. Available for remote or hybrid roles.",
    skills: "Python, Spark, Kafka, dbt, Snowflake, Databricks, SQL", location: "Shanghai, China", yearsExperience: 7, monthlyRate: 11000, availability: "available", categories: "tech,saas,analytics,data",
  },
];

export async function seedIfEmpty() {
  try {
    // Seed categories
    const [catCount] = await db.select({ c: count() }).from(categoriesTable);
    if (Number(catCount.c) === 0) {
      await db.insert(categoriesTable).values(CATEGORIES);
      logger.info("Seeded categories");
    }

    // Seed locations
    const [locCount] = await db.select({ c: count() }).from(locationsTable);
    if (Number(locCount.c) === 0) {
      await db.insert(locationsTable).values(LOCATIONS);
      logger.info("Seeded locations");
    }

    // Seed jobs
    const [jobCount] = await db.select({ c: count() }).from(jobsTable);
    if (Number(jobCount.c) === 0) {
      await db.insert(jobsTable).values(JOBS);
      logger.info("Seeded jobs");
    }

    // Seed startup ideas
    const [ideaCount] = await db.select({ c: count() }).from(startupIdeasTable);
    if (Number(ideaCount.c) === 0) {
      await db.insert(startupIdeasTable).values(STARTUP_IDEAS);
      logger.info("Seeded startup ideas");
    }

    // Seed candidates
    const [candCount] = await db.select({ c: count() }).from(candidatesTable);
    if (Number(candCount.c) === 0) {
      await db.insert(candidatesTable).values(CANDIDATES);
      logger.info("Seeded candidates");
    }
  } catch (err) {
    logger.error({ err }, "Error during seeding");
  }
}
